### ISSUE TITLE
Being able to watch private channels

### ISSUE THREAD

**Issue by Areax** [xates/tg-channel-watcher#2]
Something cute I thought of (I cloned your repo and edited it to be able to broaden what `channel_names` can be):

```python
for channel in channel_names:
	try:
		value = int(channel)
		client(JoinChannelRequest(client.get_input_entity(value)))
	except ValueError:
		client(JoinChannelRequest(client.get_input_entity(channel)))
```
this allows me to have `channel_names` also be the 13 digit strings with a negative in the front (private channels).  Currently, when you try pass `channel` into `get_input_entity`, it removed the negative value (if the string is a number) and throws an error.

**Comment by xates** [comment]
As you suggested I have added support for private channels, however, I have implemented it a bit differently.

I have rewritten a big portion of the script so that now in the config file you can assign to the parameter `channels` (before it was `channel_names`) both usernames (for public channels) and invite links (for private channels).
