### ISSUE TITLE
Can't write in my own chat O.o

### ISSUE THREAD

**Issue by sh4d0w131** [xates/tg-channel-watcher#3]
I keep getting this error.

http://prntscr.com/ihrefa

**Comment by xates** [comment]
What were you trying to do? Which piece of code is causing this? Is that photo the full traceback of the error? Please provide me something so that I can reproduce this because forwarding messages to myself works just fine for me.

Anyway, I have just updated the code to support the latest version of Telethon so you might want to try with that new version.
